### ISSUE TITLE
c++ exceptions under the hood part 1 incorrect link to part 4

### ISSUE THREAD

**Issue by adrianpp** [nicolasbrailo/nicolasbrailo.github.io#1]
https://github.com/nicolasbrailo/nicolasbrailo.github.io/blob/585801ec391b9fe7493531910e4d8fbb3cfa1e27/md_blog/projects_texts/index.md?plain=1#L128

This is a link to part 4 - it should be a link to part 1:

https://nicolasbrailo.github.io/blog/2013/0205_Cexceptionsunderthehood.html

**Comment by nicolasbrailo** [comment]
Hi @adrianpp! This is beyond awesome, thanks a lot for reporting - and even bigger thanks for reading through my rants and random texts. Hope you found something useful, or at least fun to read.
